### ISSUE TITLE
Visualizer not working on Mac

### ISSUE THREAD

**Issue by ChristianWiele** [Unity-Technologies/com.unity.perception#460]
Hi,

any time I try to open the visualizer on Mac, I get the notification that it is not installed. When I select to install it, I get the message "Successfully installed visualizer tool!", but then I get a warning "Failed to get visualizer process ID ..." and nothing happens. 
The Python for Unity package seems to work fine. I can open the console and execute Python statements.

Christian

Unity 2020.3.32
Perception 0.10.0-preview.1

**Comment by aryan-mann** [comment]
Hey @ChristianWiele! Just wanted to let you know that I was able to reproduce the issue on a Mac today and we are currently identifying the cause. Should be fixed in the next patch release!

- Aryan

**Comment by JonathanHUnity** [comment]
A new version of the package has been released that should fix this issue. Please give it a shot and re-open if it is not fixed. Thanks!

**Comment by ChristianWiele** [comment]
Just tried the new version on Unity 2020.3.33 / Mac, and the issue is still there. Same behavior.

**Comment by Robotatron** [comment]
> A new version of the package has been released that should fix this issue. Please give it a shot and re-open if it is not fixed. Thanks!

Where can we download the new version? The latest commit here is for 0.11.1-preview.1 and that is the version I am having right now 
![image](https://user-images.githubusercontent.com/95919873/164350374-83b12372-b4e8-44d6-a9d2-f3fcca04cd23.png)
